feature:팀 강퇴 기능 추가
khanturtle/WeMakePlay pull request #36
Opened 2024-01-10 06:29 UTC by Medayss

되다가 안되다가 하는데 실행에는 문제 없습니다..

2024-01-10 06:55 UTC, khanturtle requested changes

2024-01-10 06:55 UTC, khanturtle commented on src/main/java/com/wemakeplay/wemakeplay/domain/board/entity/Board.java
> +    }
요건 없어도 될 것 같습니다

2024-01-10 06:55 UTC, khanturtle commented on src/main/java/com/wemakeplay/wemakeplay/domain/board/entity/Board.java
> +    }
유저가 여러 보드에도 속할 수 있기 때문에
유저와 보드사이 관계는 중간 테이블을 통해서 처리해야할 것 같습니다

2024-01-10 06:55 UTC, khanturtle approved these changes

2024-01-11 07:19 UTC, KoKwangJu approved these changes

2024-01-11 07:23 UTC, minhyeongKang approved these changes

2024-01-11 07:27 UTC, merged